"""
Author: Supath Dhital
Date Updated: May 2026

Burn OSM-derived bridge deck elevations into the zeroed/masked HAND raster so
that bridges do not appear as flood-prone valleys in the final FIM product.

Two bridge classes are handled separately because their elevation sources
differ:

  - Non-LiDAR bridges (``has_lidar_tif == 'N'``)
      Buffer each bridge centerline by ``non_lidar_buffer`` metres and burn the
      maximum HAND value inside the buffer back over the deck footprint. The
      assumption is that the surrounding terrain HAND is a reasonable proxy
      for the deck-top HAND when no lidar capture is available.

  - LiDAR bridges (``has_lidar_tif == 'Y'``)
      Add the per-cell ``bridge_elev_diff`` raster (deck-elevation minus
      bare-earth DEM, generated by ``BridgeDEMDiff``) to the HAND raster, then
      sample the median HAND in a tight ``lidar_buffer`` around each deck.

After the HAND raster is updated in place, the bridge centroids are joined
to the crosswalked catchments to attach HydroID / feature_id metadata and a
``threshold_hand_75`` field (75 % of the threshold) used by downstream
threatened-bridge reporting.

Inputs
------
hand_raster        : rem_zeroed_masked_{id}.tif  (overwritten in place)
bridge_diff_raster : bridge_elev_diff_meters_{id}.tif (optional, for LiDAR class)
bridges_gpkg       : osm_bridges_subset.gpkg
catchments_gpkg    : gw_catchments_reaches_filtered_addedAttributes_crosswalked_{id}.gpkg

Outputs
-------
out_centroids_gpkg : osm_bridge_centroids_{id}.gpkg
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Optional, Union

import geopandas as gpd
import numpy as np
import pandas as pd
import rasterio
from rasterio import features
from rasterio.warp import Resampling, reproject

log = logging.getLogger(__name__)

PathLike = Union[str, Path]

_THREATENED_PERCENT = 0.75


def heal_bridges_osm(
    hand_raster: PathLike,
    bridges_gpkg: PathLike,
    catchments_gpkg: PathLike,
    out_centroids_gpkg: PathLike,
    bridge_diff_raster: Optional[PathLike] = None,
    non_lidar_buffer: float = 10.0,
    lidar_buffer: float = 1.5,
) -> Optional[Path]:
    """
    Heal HAND for OSM bridges. Returns the bridge-centroids path on success
    or None when there are no inputs to process.
    """
    hand_raster = Path(hand_raster)
    bridges_gpkg = Path(bridges_gpkg)
    catchments_gpkg = Path(catchments_gpkg)
    out_centroids_gpkg = Path(out_centroids_gpkg)
    out_centroids_gpkg.parent.mkdir(parents=True, exist_ok=True)
    if bridge_diff_raster is not None:
        bridge_diff_raster = Path(bridge_diff_raster)

    if not hand_raster.exists():
        log.warning("heal_bridges_osm: HAND raster missing — %s", hand_raster)
        return None
    if not bridges_gpkg.exists():
        log.info("heal_bridges_osm: no OSM bridges file — %s", bridges_gpkg)
        return None

    osm_gdf = gpd.read_file(str(bridges_gpkg))
    if osm_gdf.empty:
        log.info("heal_bridges_osm: bridges file is empty")
        return None
    osm_gdf["centroid_geometry"] = osm_gdf.centroid

    with rasterio.open(str(hand_raster), "r") as hand_ds:
        hand_profile = hand_ds.profile
        hand_array = hand_ds.read(1)
        if osm_gdf.crs != hand_ds.crs:
            osm_gdf = osm_gdf.to_crs(hand_ds.crs)

    non_lidar_gdf, hand_array = _process_non_lidar(
        osm_gdf, hand_array, hand_profile, non_lidar_buffer
    )
    lidar_gdf, hand_array = _process_lidar(
        osm_gdf, hand_array, hand_profile, lidar_buffer, bridge_diff_raster
    )

    parts = [g for g in (non_lidar_gdf, lidar_gdf) if g is not None and len(g) > 0]
    if not parts:
        log.info("heal_bridges_osm: no usable bridges after processing")
        return None
    healed = pd.concat(parts, ignore_index=True)

    # Persist the updated HAND raster.
    with rasterio.open(str(hand_raster), "w", **hand_profile) as out_ds:
        out_ds.write(hand_array, 1)

    # Switch to centroid geometry and attach catchment / feature_id metadata.
    healed = gpd.GeoDataFrame(
        healed.drop(columns=["geometry"]).assign(geometry=healed["centroid_geometry"]),
        crs=hand_profile["crs"],
    )
    healed = healed.drop(columns=["centroid_geometry"])
    healed = healed.loc[healed["threshold_hand"] > 0]

    catchments_df = gpd.read_file(str(catchments_gpkg), engine="fiona")
    if catchments_df.crs != healed.crs:
        catchments_df = catchments_df.to_crs(healed.crs)
    join_cols = [c for c in ("HydroID", "feature_id", "order_") if c in catchments_df.columns]
    healed = gpd.sjoin(
        healed, catchments_df[join_cols + ["geometry"]], how="inner"
    ).drop(columns=["index_right"])

    healed["threshold_hand_75"] = healed["threshold_hand"] * _THREATENED_PERCENT

    branch_id = _branch_id_from_path(out_centroids_gpkg)
    healed["branch"] = branch_id
    healed["mainstem"] = 0 if branch_id == "0" else 1

    if healed.empty:
        log.info("heal_bridges_osm: bridges did not intersect any catchment")
        return None

    if out_centroids_gpkg.exists():
        out_centroids_gpkg.unlink()
    healed.to_file(str(out_centroids_gpkg), index=False, engine="fiona", driver="GPKG")
    log.info("heal_bridges_osm: wrote %d bridges → %s", len(healed), out_centroids_gpkg.name)
    return out_centroids_gpkg


# Internal helpers
def _require_zonal_stats():
    """Import rasterstats lazily so the rest of the pipeline can run without it."""
    try:
        from rasterstats import zonal_stats  # noqa: F401
        return zonal_stats
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Bridge / road FIMpact requires the 'rasterstats' package. "
            "Install with: pip install rasterstats"
        ) from exc


def _process_non_lidar(
    osm_gdf: gpd.GeoDataFrame,
    hand_array: np.ndarray,
    hand_profile: dict,
    buffer_m: float,
) -> tuple[Optional[gpd.GeoDataFrame], np.ndarray]:
    """Burn max-HAND-in-buffer back over each non-LiDAR bridge footprint."""
    if "has_lidar_tif" in osm_gdf.columns:
        non_lidar = osm_gdf[osm_gdf["has_lidar_tif"] == "N"].copy()
    else:
        non_lidar = osm_gdf.copy()

    if non_lidar.empty:
        return None, hand_array

    non_lidar["geometry"] = non_lidar.geometry.buffer(buffer_m, resolution=int(buffer_m))

    zonal_stats = _require_zonal_stats()
    stats = zonal_stats(
        non_lidar["geometry"],
        hand_array,
        affine=hand_profile["transform"],
        stats="max",
        nodata=hand_profile.get("nodata"),
        all_touched=True,
    )
    non_lidar["threshold_hand"] = [s.get("max") for s in stats]
    non_lidar = non_lidar.sort_values(by="threshold_hand", ascending=False)

    shapes = (
        (geom, val)
        for geom, val in zip(non_lidar.geometry, non_lidar["threshold_hand"])
        if geom is not None and val is not None
    )
    features.rasterize(
        shapes=shapes,
        out=hand_array,
        transform=hand_profile["transform"],
        all_touched=False,
    )
    return non_lidar, hand_array


def _process_lidar(
    osm_gdf: gpd.GeoDataFrame,
    hand_array: np.ndarray,
    hand_profile: dict,
    buffer_m: float,
    diff_raster: Optional[Path],
) -> tuple[Optional[gpd.GeoDataFrame], np.ndarray]:
    """Add the bridge_elev_diff raster to HAND, then sample median HAND on each deck."""
    if "has_lidar_tif" not in osm_gdf.columns:
        return None, hand_array
    lidar = osm_gdf[osm_gdf["has_lidar_tif"] == "Y"].copy()
    if lidar.empty:
        return None, hand_array
    if diff_raster is None or not Path(diff_raster).exists():
        log.warning(
            "heal_bridges_osm: %d LiDAR bridges present but no diff raster — skipping",
            len(lidar),
        )
        return None, hand_array

    with rasterio.open(str(diff_raster)) as diff_ds:
        diff_arr = diff_ds.read(1)
        diff_transform = diff_ds.transform
        diff_crs = diff_ds.crs

    if (
        hand_profile["crs"] != diff_crs
        or hand_profile["transform"] != diff_transform
        or hand_array.shape != diff_arr.shape
    ):
        diff_resampled = np.empty_like(hand_array, dtype=diff_arr.dtype)
        reproject(
            source=diff_arr,
            destination=diff_resampled,
            src_transform=diff_transform,
            src_crs=diff_crs,
            dst_transform=hand_profile["transform"],
            dst_crs=hand_profile["crs"],
            dst_shape=hand_array.shape,
            resampling=Resampling.nearest,
        )
    else:
        diff_resampled = diff_arr

    nodata_value = hand_profile.get("nodata")
    updated = np.where(
        (hand_array == nodata_value) | (diff_resampled == nodata_value),
        nodata_value,
        hand_array + diff_resampled,
    )

    lidar["geometry"] = lidar.geometry.buffer(buffer_m, resolution=int(buffer_m))

    zonal_stats = _require_zonal_stats()
    stats = zonal_stats(
        lidar["geometry"],
        updated,
        affine=hand_profile["transform"],
        stats="median",
        nodata=nodata_value,
        all_touched=True,
    )
    lidar["threshold_hand"] = [s.get("median") for s in stats]
    return lidar, updated


def _branch_id_from_path(path: Path) -> str:
    """Pick the branch id out of a ``branches/<id>/`` path, or 0 when absent."""
    m = re.search(r"branches/(\d{10}|0)/", str(path))
    if m:
        return m.group(1)
    return "0"
