"""
Author: Supath Dhital
Date Updated: August 2026

Generated by the calibration-data build tool -- do not edit by hand.

Maps every published calibration dataset to its S3-relative path and SHA256.
"""

from __future__ import annotations

DATASETS: tuple[str, ...] = (
    "bankfull_flows",
    "channel_bathymetry",
    "channel_geometry_predicted",
    "channel_roughness",
    "flood_edge_points",
    "gage_locations",
    "gage_quality_filter",
    "gage_rating_curves",
    "manual_coefficients",
    "reach_slope",
    "recurrence_flows",
    "xsec_locations",
    "xsec_rating_curves",
)

# S3-relative path -> sha256 of the published object.
REGISTRY: dict[str, str] = {
    "national/bankfull_flows.parquet": "dfce2f6173a680525ae247e533d976f77952b50a9c5e2a86938dc2275105d492",
    "national/channel_bathymetry.parquet": "9dbb4fa6df56ade9d6e7c3e188d6477bdd637c04b501a604fa18bab21a9d5abc",
    "national/channel_geometry_predicted.parquet": "574e3c2aba2aea6231c76b48212c3cc3fa6eb0adebeced1c6bea1dab60e9dae7",
    "national/channel_roughness.parquet": "49403e2765237bfba2b718ae363bec2506d7ea282c2fe8aac4919ab7e1099249",
    "national/flood_edge_points.parquet": "3a2ac8037895d6e8aae046983024026a75b1605a847bbf6d7c2f29d0726d0d63",
    "national/gage_locations.parquet": "5690de82b3787eacc402ac6ee8e8446a0fa207a7af71e106599cc23adbc7dbfb",
    "national/gage_quality_filter.parquet": "12ecc7fb6dac334ec1d2a697dd09bb1db36b5263224f2de4128be5595895ac48",
    "national/gage_rating_curves.parquet": "e62ae702f4d0cdec11693fab0bda2f8bfe571ab6e87ef5b42f21324d4fad46f8",
    "national/manual_coefficients.parquet": "e4b0666e06df5188e0b688f7bccc6eb554f31dea4943b524eeb9da467ce33ead",
    "national/reach_slope.parquet": "08725a529cfa97566e6294353be76fa171b667255499caa510ad32fe08ab6177",
    "national/recurrence_flows.parquet": "d0fc48ffc4f2e719a755af3754d08bd899637f0714764e8016e4feb9d7affc75",
    "national/xsec_locations.parquet": "66cc1f2eeb63afd930b69fc6d0120747c74244375576eaa3a73863674c56b566",
    "national/xsec_rating_curves.parquet": "de1e027233704c08b013d2272a999843f7bb78be863675ff12342aa0f6d35c01",
}
